version: '3'
services:
  db:
    image: mcr.microsoft.com/azure-sql-edge-developer:latest
    environment:
      SA_PASSWORD: "db_password123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
  mail:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
      - mail
    env_file:
      - .env
